#!/bin/bash

read -p "gift_id: " gift_id
read -p "item_name: " item_name
read -p "price: " price
read -p "to: " to
read -p "from: " from

curl -i -H "Content-Type: application/json" -X PUT -d '{"item_name": "'$item_name'", "price": "'$price'", "to": "'$to'", "from": "'$from'"}' -c cookie-jar -k http://info3103.cs.unb.ca:36371/users/$from/gifts/$gift_id
