#%RAML 1.0
title: Present Registry
version: v0.01
baseUri: http://info3103.cs.unb.ca:36371/project
types:
  URI: string
  user:
    type: object
    properties:
      user_id:
        type: string
        required: false
      first_name: string
      last_name:  string
  gift:
    type: object
    properties:
      gift_id:
        type: string
        required: false
      item_name:  string
      price:      number
      to:         string
      from:       string
  credentials:
    type: object
    properties: 
      username: string
      password: string
  account:
    type: object
    properties:
      user_id:
        type: string
        required: false
      first_name: string
      last_name: string
      username: string
      password: string

/users:
  get:
    description: get a list of users registered in the application
    responses:
      200:
        body:
          application/json:
            type: user[]
            example: |
              [
                {
                  "user_id": "fdecdb4f-dbd7-11e8-b6a5-3065ec6fbf23",
                  "first_name": "Tom",
                  "last_name": "Segura"
                },
                {
                  "user_id": "fdecdb4f-dbd7-11e8-b6a5-8d0a3ddafd2",
                  "first_name": "Bill",
                  "last_name": "Burr"
                }
              ]
      404:
  
  post:
    description: register a user into the system
    body:
      application/json:
        type: account
        example: 
          {
            "first_name": "Bill",
            "last_name": "Burr",
            "username": "bburr",
            "password": "abc123"
          }
    responses:
      200:
        body:
          application/json:
            type: user
            example:
              {
                "user_id": "fdecdb4f-dbd7-11e8-b6a5-8d0a3ddafd2",
                "first_name": "Bill",
                "last_name": "Burr",
              }
      404:

  /{user_id}:
    get:
      description: get a user resource with `user_id`
      responses:
        200:
          body:
            application/json:
              type: user
              example: |
                {
                  "user_id": "fdecdb4f-dbd7-11e8-b6a5-8d0a3ddafd2",
                  "first_name": "Bill",
                  "last_name": "Burr"
                }
        403:
        404:
    put:
      description: updates the information of the user specified with `user_id`
      body:
        application/json:
          type: user
          example: |
              {
                "user_id": "fdecdb4f-dbd7-11e8-b6a5-8d0a3ddafd2",
                "first_name": "Billy",
                "last_name": "Burr"
              }
      responses:
        204:
          body:
            application/json:
              type: user
              example: |
                {
                  "user_id": "fdecdb4f-dbd7-11e8-b6a5-8d0a3ddafd2",
                  "first_name": "Bill",
                  "last_name": "Burr"
                }
        404:
        400:

    /gifts:
      description: collection of gifts registered the application

      get:
        description: retrieves a list of gifts linked to the user defined in `user_id`
        queryParameters:
          to:
            description: name of the user that sent the gift
            type: string
            required: false
        responses:
          200:
            body:
              application/json:
                type: gift[]
                example: |
                  [
                    {
                      "gift_id": "fdecdb4f-dbd7-11e8-b6a5-8d0a3ddafd2",
                      "to": "Tom",
                      "from": "Morgan",
                      "item_name": "car",
                      "price": 30000
                    },
                    {
                      "gift_id": "fdecdb4f-dbd7-11e8-b6a5-8d0a3ddafd2",
                      "to": "Mark",
                      "from": "Teresa",
                      "item_name": "laptop",
                      "price": 1200
                    }
                  ]
      post:
        description: creates a new gift resource for the user defined by `user_id`
        responses:
          200:
            body:
              application/json:
                type: gift
                example: |
                  {
                    "gift_id": "fdecdb4f-dbd7-11e8-b6a5-8d0a3ddafd2",
                    "to": "Mark",
                    "from": "Albert",
                    "item_name": "laptop",
                    "price": 1200
                  }
          403:
          400:
        body:
          application/json:
              type: gift
              example: |
                {
                  "to": "Mark",
                  "from": "Albert",
                  "item_name": "laptop",
                  "price": 1200
                }
      /{gift_id}:
        get:
          description: retrieve gift resource specified by `gift_id`
          responses:
            200:
              body:
                application/json:
                  type: gift
                  example: |
                    {
                      "gift_id": "fdecdb4f-dbd7-11e8-b6a5-8d0a3ddafd2",
                      "to": "Mark",
                      "from": "Albert",
                      "item_name": "laptop",
                      "price": 1200
                    }
            404:
        put:
          description: modify gift resource specified by `user_id`
          body:
            application/json:
              type: gift
              example: |
                {
                  "to": "Mark",
                  "from": "Albert",
                  "item_name": "acer laptop",
                  "price": 1200
                }
          responses:
            200:
              body:
                application/json:
                  type: gift
                  example: |
                    {
                      "gift_id": "fdecdb4f-dbd7-11e8-b6a5-8d0a3ddafd2",
                      "to": "Mark",
                      "from": "Albert",
                      "item_name": "acer laptop",
                      "price": 1200
                    }
            404:
        delete:
          description: delete a gift resource
          responses:
            204:

/gifts:
  description: collection of gift resources

  get:
    description: retrieves a list of all gift resources
    queryParameters: 
      user_id: string
    responses: 
      200:
        body:
          application/json:
            example: |
              [
                {
                  "gift_id": "fdecdb4f-dbd7-11e8-b6a5-8d0a3ddafd2",
                  "to": "Mark",
                  "from": "Albert",
                  "item_name": "acer laptop",
                  "price": 1200
                },
                {
                  "gift_id": "fdecdb4f-dbd7-11e8-b6a5-7as56d5fas",
                  "to": "Laura",
                  "from": "Morgan",
                  "item_name": "iphone x",
                  "price": 1000
                }
              ]

/login:
  description: manages login mechanism

  post:
    description: logs in a user
    body:
      application/json:
        type: credentials
        example: |
          {
            "username": "mzuckerberg",
            "password": "abc123"
          }
    responses:
      200:
      404:
  
  delete:
    description: logs out a user
    responses:
      204: