DROP TABLE IF EXISTS gifts;
DROP TABLE IF EXISTS users;
CREATE TABLE users(
  user_id VARCHAR(50) NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  PRIMARY KEY(user_id)
);